sudo: required

language: generic

services:
 - docker

before_install:
 - docker build -t myapp1 -f Dockerfile.dev .

cache: npm

script:
 - "travis_wait 20 sleep 1800 &"
 - docker run myapp1 npm run test -- --coverage | return 0;
 
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-849989103501'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY