sudo: required

language: generic

services:
 - docker

before_install:
 - docker build -t myapp1 -f Dockerfile.dev .

cache: npm

script:
 - docker run myapp1 npm run test -- --coverage
 - "travis_wait 20 sleep 1800 &"